### ISSUE TITLE
some problems in running core test (make runTests)

### ISSUE THREAD

**Issue by study0098** [MarcToussaint/rai#4]
Hello, your great robotics AI is really charming. But there is a small problem after compiling this repo (after make), that is, the user needs to put the folder 'rai-robotModels' in the same directory as this repo (one directory, containing 2 folders), or the test programs cannot find the relative model files.  An example is that when running test/LGP/pickAndPlace, it will always fail without 'rai-robotModels'. 

Moreover, there are some test case that I cannot pass, e.g. , test/Optim/ipopt, test/Optim/ceres, test/Logic/fol, etc.. I assume that this is because the lack of relative dependencies, but I'm not sure about the specific name and installation. Actually, I've installed Ceres, but as mentioned above the test about ceres fails. Do I need to install all the dependencies listed in config.mk to get this repo fully worked? I'm a bit worry about it since installations of various dependencies are onerous.

Below are my output when running 'make runTests', and the content of config.mk. 
`* Running  test/Geo/geo

         * Running  test/Geo/convex

         * Running  test/Geo/PairCollisions

         * Running  test/Geo/mesh

         * Running  test/KOMO/komo

         * Running  test/KOMO/switches

         * Running  test/KOMO/tutorial

         * Running  test/KOMO/seq

         * Running  test/Core/array

         * Running  test/Core/graph

         * Running  test/Core/thread

         * Running  test/Core/util

         * Running  test/Gui/opengl_windowless

         * Running  test/Gui/opengl_mini

         * Running  test/Gui/opengl_threaded

         * Running  test/Gui/projections

         * Running  test/Gui/opengl

         * Running  test/Optim/optim

         * Running  test/Optim/ipopt

     ***** FAILED   test/Optim/ipopt  with return code  1

         * Running  test/Optim/KOMO_problem

         * Running  test/Optim/nlopt

         * Running  test/Optim/constrained

         * Running  test/Optim/ceres

     ***** FAILED   test/Optim/ceres  with return code  134

         * Running  test/Logic/relationalMachine

         * Running  test/Logic/player

         * Running  test/Logic/fol

     ***** FAILED   test/Logic/fol  with return code  134

         * Running  test/Logic/pddl

     ***** FAILED   test/Logic/pddl  with return code  134

         * Running  test/Kin/CameraView

         * Running  test/Kin/pairCollision_jacobians

         * Running  test/Kin/features

         * Running  test/Kin/kin

     ***** FAILED   test/Kin/kin  with return code  134

         * Running  test/Kin/physx

     ***** FAILED   test/Kin/physx  with return code  1

         * Running  test/Kin/dynamics

     ***** FAILED   test/Kin/dynamics  with return code  134    

         * Running  test/Kin/assimp  

     ***** FAILED   test/Kin/assimp  with return code  134  

         * Running  test/Kin/SSB_distance  

         * Running  test/Kin/swift  

         * Running  test/Algo/splines  

         * Running  test/Algo/ML-regression  

         * Running  test/Algo/ann  

         * Running  test/LGP/pickAndPlace  

     ***** TIMEOUT  test/LGP/pickAndPlace  `
config.mk:
`#OPTIM = debug
#OPTIM = fast_debug

#GL = 0
OPENCV = 0
GRAPHVIZ = 0
GTK = 0
G4 = 0
PYBIND = 0
PNG = 0

#EIGEN = 0
#CERES = 0
#NLOPT = 0
#IPOPT = 0

FCL = 0
PCL = 0
ODE = 0
PHYSX = 0
BULLET = 0
BULLET_UBUNTU = 0

ROS = 0
ROS_VERSION = melodic`

**Comment by MarcToussaint** [comment]
Thank you for the comment, study0098!
You are right with all you're saying. I haven't updated the README lately and what you found should be better explained there. The rai repo is a module that we use in many internal projects, which typically include the rai as submodule next to some others, such as rai-robotModels.
You're also right about the dependencies: the pretty old-fashioned make system is very flexible to turn on/off dependencies, but not understandable for users. Many of our root repos use other make systems to compile the rai module, e.g. cmake.
The ceres interface would require to have ceres as parallel submodule. Some of our optimization projects have this properly configured, and I'll soon have the optimization-course repo link to this properly with running test (I'm teaching the course this term). If interested in the optimization interfaces, have a look at that repo in about 2 weeks.

**Comment by study0098** [comment]
Thank you very much for your elaboration!  Looking forward to the optimization-course repo!
