### ISSUE TITLE
Missing k_order in ry KOMO.setConfigurations?

### ISSUE THREAD

**Issue by whoenig** [MarcToussaint/rai#6]
https://github.com/MarcToussaint/rai/blob/b4e7082f3b7e8be5a0490f37e57d442047aaa020/rai/ry/ry-KOMO.cpp#L167

I think this is missing `k_order`, i.e., the line should be:

```
self->pathConfig.setFrameState( X, self->timeSlices[self->k_order + t] );
```

This at least fixes the 'redo optimization' example in [3-IK-optimization.ipynb](https://github.com/MarcToussaint/rai-python/blob/master/tutorials/3-IK-optimization.ipynb).

I can create a pull request if that is easier/preferred.

**Comment by MarcToussaint** [comment]
True. Is already fixed in 'marc' branch. Will be merged some time.
